services:
  # Anvil - Foundry's local blockchain.
  anvil:
    container_name: anvil
    image: ghcr.io/foundry-rs/foundry:v1.2.2
    ports: ["8545:8545"]
    entrypoint: >
      sh -c '
        BLOCK_NUMBER=$(cast block-number --rpc-url "$$RPC_URL") && \
        anvil --host 0.0.0.0 --block-time 1 --silent \
              --fork-url "$$RPC_URL" \
              --fork-block-number "$$BLOCK_NUMBER"
      '
    environment:
      - RPC_URL
    platform: linux/amd64/v8
    healthcheck:
      test: ["CMD-SHELL", "cast rpc web3_clientVersion | grep -c anvil > /dev/null "]
      start_interval: 250ms
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 50